//****$
//***$*
//**$**
//*$***
//$****
//
#include<stdio.h>
main(){
	int row,col;
	for (row=1;row<=1;row++)
	{
		for(col=1;col<=1;col++){
			printf("****$");
		}{
		printf("\n");
		}
	for(col=1;col<=1;col++){
			printf("***$*");
		}{
		printf("\n");
		}for(col=1;col<=1;col++){
			printf("**$**");
		}{
		printf("\n");
		}for(col=1;col<=1;col++){
			printf("*$***");
		}{
		printf("\n");
		}for(col=1;col<=1;col++){
			printf("$****");
		}{
		printf("\n");
		}
		}
		printf("\n");
	}
